const fabrics = [
  {
    id: 1,
    image:
      'https://images.squarespace-cdn.com/content/v1/5961c8ce3e00be4fb1decc32/1603783100355-FNSY9GXHGDC0HAA21LUB/Screen+Shot+2020-10-27+at+3.16.14+PM.png?format=750w',
    name: 'The Textile Atlas',
    city: 'Angkor, Cambodia',
    location: 'HWMC+7H Phnom Penh, Cambodia',
    link: 'https://www.thetextileatlas.com/',
  },
  {
    id: 2,
    image: 'http://www.gogoindia.com/images/slide1.JPG',
    name: 'Go Go International',
    city: 'Bangalore, India',
    location: 'XH7G+5C Bengaluru, Karnataka, India',
    link: 'http://www.gogoindia.com/index.php',
  },
  {
    id: 3,
    image: 'https://i.postimg.cc/pX3Lx1sL/2021-09-02-16-12-12.png',
    name: 'Tailor Brands',
    city: 'Brooklyn, NY, USA',
    location: 'P243+C7 New York, United States',
    link: 'https://www.tailorbrands.com/',
  },
  {
    id: 4,
    image: 'https://i.postimg.cc/CLnwvswT/2021-09-02-16-12-19.png',
    name: 'Ocean-de-Fashion',
    city: 'Delhi, India',
    location: 'J6G5+JJ New Delhi, Delhi, India',
    link: 'https://www.globalsources.com/',
  },
  {
    id: 5,
    image: 'https://i.postimg.cc/wMh0vrhY/2021-09-02-16-09-11.png',
    name: 'Pashmina',
    city: 'Gurugram, India',
    location: 'F28C+2J Gurugram, Haryana, India',
    link: 'https://www.pashmina.com/',
  },
  {
    id: 6,
    image:
      'https://www.sgdistributors.co.za/assets/images/content/glasses1.jpg',
    name: 'Distributors',
    city: 'Johannesburg, South Africa',
    location: 'Q2VW+XR Johannesburg, South Africa',
    link: 'https://www.sgdistributors.co.za/',
  },
  {
    id: 7,
    image: 'http://shanthiknitss.com/images/slider/0444.jpg',
    name: 'Shanthi Knitss',
    city: 'Tamil Nadu, India',
    location: 'JH2X+7C Attur, Tamil Nadu, India',
    link: 'http://shanthiknitss.com/',
  },
  {
    id: 8,
    image: 'https://i.postimg.cc/MG9kZnzm/2021-09-02-16-12-34.png',
    name: 'Tikam Fashions',
    city: 'Mumbai, India',
    location: '3VWR+82 Mumbai, Maharashtra, India',
    link: 'https://tikamfashions.tripod.com/index.html',
  },
  {
    id: 9,
    image: 'https://i.postimg.cc/FHDmzWZS/2021-09-02-16-15-03.png',
    name: 'RGR Knitwear',
    city: 'Tiruppur, India',
    location: '4954+8M Tiruppur, Tamil Nadu, India',
    link: 'http://rgrknitwear.com/index.php',
  },
  {
    id: 10,
    image: 'https://i.postimg.cc/FzdXBh5g/2021-09-02-16-12-28.png',
    name: 'Justdial',
    city: 'Delhi, India',
    location: 'J6G5+JJ New Delhi, Delhi, India',
    link: 'https://www.justdial.com/',
  },
];

export default fabrics;
